### ISSUE TITLE
 GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

### ISSUE THREAD

**Issue by nanangsb** [javawebmedia/websitesekolah#1]
CodeIgniter\Database\Exceptions\DatabaseException #1055
Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'javawebmedia_sekolah.berita.icon' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
![Screenshot_2024-02-02-17-34-57-433_com android chrome](https://github.com/javawebmedia/websitesekolah/assets/8703377/a438428f-cab5-4bea-84f7-84d58fa46b0e)
![Screenshot_2024-02-02-17-34-52-502_com android chrome](https://github.com/javawebmedia/websitesekolah/assets/8703377/e6ab8bcf-e1be-43ae-a491-a77942efc08c)
![Screenshot_2024-02-02-17-34-43-154_com android chrome](https://github.com/javawebmedia/websitesekolah/assets/8703377/2e3886c9-9fe8-4a47-8877-5159312021e7)

**Comment by javawebmedia** [comment]
Change your SQL Mode. Remove SQL_FULL_GROUP_BY
